### ISSUE TITLE
Simplify Endpoint Definition

### ISSUE THREAD

**Issue by bbilger** [bbilger/jrestless-examples#2]
Change from:
```yaml
# serverless.yml
functions:
  fnname:
    handler: someHandler
    events:
      - http:
          path: api/{proxy+}
          method: any
```
to:
```yaml
# serverless.yml
functions:
  fnname:
    handler: someHandler
    events:
      - http: ANY api/{proxy+}
```
